/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Metas_Macro_GUI extends javax.swing.JFrame {

    /**
     * Creates new form home_DGV_GUI
     */
    public Metas_Macro_GUI() {
        initComponents();
        
        try {
            model.database_metas_DAO.carregaMetas();
        } catch (SQLException ex) {
            Logger.getLogger(Metas_Macro_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        Copyright = new javax.swing.JLabel();
        botaoGastos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        botaoMetas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        botaoSair = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        registros = new javax.swing.JTable();
        titulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagina Inicial");
        setUndecorated(true);

        FundoPrincipal.setBackground(new java.awt.Color(243, 243, 243));
        FundoPrincipal.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(null);

        botaoDashboard.setBackground(new java.awt.Color(228, 228, 228));
        botaoDashboard.setToolTipText("Gerenciar registro de chaves.");
        botaoDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDashboardMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("DASHBOARD");

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botaoDashboardLayout = new javax.swing.GroupLayout(botaoDashboard);
        botaoDashboard.setLayout(botaoDashboardLayout);
        botaoDashboardLayout.setHorizontalGroup(
            botaoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoDashboardLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        botaoDashboardLayout.setVerticalGroup(
            botaoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botaoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(botaoDashboard);
        botaoDashboard.setBounds(10, 160, 260, 50);

        Copyright.setText("@YasNikki");
        jPanel1.add(Copyright);
        Copyright.setBounds(10, 454, 240, 20);

        botaoGastos.setBackground(new java.awt.Color(228, 228, 228));
        botaoGastos.setToolTipText("Gerenciar registro de itens.");
        botaoGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoGastosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoGastosMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("GASTOS/GANHOS");

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fluxo-de-dinheiro.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botaoGastosLayout = new javax.swing.GroupLayout(botaoGastos);
        botaoGastos.setLayout(botaoGastosLayout);
        botaoGastosLayout.setHorizontalGroup(
            botaoGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoGastosLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        botaoGastosLayout.setVerticalGroup(
            botaoGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botaoGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(botaoGastos);
        botaoGastos.setBounds(10, 220, 260, 50);

        botaoMetas.setBackground(new java.awt.Color(204, 204, 204));
        botaoMetas.setToolTipText("Gerenciar dados cadastrados.");
        botaoMetas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoMetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMetasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoMetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoMetasMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("METAS");

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/growth.png"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botaoMetasLayout = new javax.swing.GroupLayout(botaoMetas);
        botaoMetas.setLayout(botaoMetasLayout);
        botaoMetasLayout.setHorizontalGroup(
            botaoMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMetasLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        botaoMetasLayout.setVerticalGroup(
            botaoMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoMetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botaoMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(panelImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(botaoMetas);
        botaoMetas.setBounds(10, 280, 260, 50);

        botaoSair.setBackground(new java.awt.Color(228, 228, 228));
        botaoSair.setToolTipText("");
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSairMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fechar Software");

        javax.swing.GroupLayout botaoSairLayout = new javax.swing.GroupLayout(botaoSair);
        botaoSair.setLayout(botaoSairLayout);
        botaoSairLayout.setHorizontalGroup(
            botaoSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoSairLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        botaoSairLayout.setVerticalGroup(
            botaoSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoSairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(botaoSair);
        botaoSair.setBounds(10, 340, 260, 50);

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_macro.png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage5);
        panelImage5.setBounds(-40, -60, 350, 230);

        FundoPrincipal.add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 490);

        registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meta", "Descrição", "Data Alvo", "Conclusão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(registros);

        FundoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(290, 10, 520, 280);
        FundoPrincipal.add(titulo);
        titulo.setBounds(300, 330, 160, 30);

        jLabel5.setText("Meta");
        FundoPrincipal.add(jLabel5);
        jLabel5.setBounds(300, 310, 160, 14);
        FundoPrincipal.add(desc);
        desc.setBounds(470, 330, 160, 30);

        jLabel6.setText("Descrição");
        FundoPrincipal.add(jLabel6);
        jLabel6.setBounds(470, 310, 160, 14);

        jLabel7.setText("Data Alvo");
        FundoPrincipal.add(jLabel7);
        jLabel7.setBounds(640, 310, 160, 14);

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FundoPrincipal.add(data);
        data.setBounds(640, 330, 160, 30);

        jButton1.setText("Registrar Meta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FundoPrincipal.add(jButton1);
        jButton1.setBounds(470, 370, 160, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Check.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FundoPrincipal.add(jButton2);
        jButton2.setBounds(640, 370, 80, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excluir.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        FundoPrincipal.add(jButton3);
        jButton3.setBounds(720, 370, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(820, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDashboardMouseEntered
        
        botaoDashboard.setBackground(new Color(153,153,153));
        
    }//GEN-LAST:event_botaoDashboardMouseEntered

    private void botaoDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDashboardMouseExited
        
        botaoDashboard.setBackground(new Color(228,228,228));
        
    }//GEN-LAST:event_botaoDashboardMouseExited

    private void botaoGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGastosMouseEntered
        
        botaoGastos.setBackground(new Color(153,153,153));
        
    }//GEN-LAST:event_botaoGastosMouseEntered

    private void botaoGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGastosMouseExited
        
        botaoGastos.setBackground(new Color(204,204,204));
        
    }//GEN-LAST:event_botaoGastosMouseExited

    private void botaoMetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMetasMouseEntered
        
        botaoMetas.setBackground(new Color(153,153,153));
        
    }//GEN-LAST:event_botaoMetasMouseEntered

    private void botaoMetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMetasMouseExited
        
        botaoMetas.setBackground(new Color(204,204,204));
        
    }//GEN-LAST:event_botaoMetasMouseExited

    private void botaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseEntered
        
        botaoSair.setBackground(new Color(153,153,153));
        
    }//GEN-LAST:event_botaoSairMouseEntered

    private void botaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseExited
        
        botaoSair.setBackground(new Color(228,228,228));
        
    }//GEN-LAST:event_botaoSairMouseExited

    private void botaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_botaoSairMouseClicked

    private void botaoMetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMetasMouseClicked
        

        
    }//GEN-LAST:event_botaoMetasMouseClicked

    private void botaoDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDashboardMouseClicked
        
        new Dashboard_Macro_GUI().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoDashboardMouseClicked

    private void botaoGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGastosMouseClicked
        
        new Gastos_Macro_GUI().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoGastosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        model.database_metas_DAO.verificaMeta();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        model.database_metas_DAO.desregistraMetas();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        model.database_metas_DAO.registraMetas();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metas_Macro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metas_Macro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metas_Macro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metas_Macro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metas_Macro_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyright;
    private javax.swing.JPanel FundoPrincipal;
    private javax.swing.JPanel botaoDashboard;
    private javax.swing.JPanel botaoGastos;
    private javax.swing.JPanel botaoMetas;
    private javax.swing.JPanel botaoSair;
    public static javax.swing.JFormattedTextField data;
    public static javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    public static javax.swing.JTable registros;
    public static javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
